version: '3.4'
services:
  mongodb:
    container_name: memohub-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    restart: always

  redis:
    container_name: memohub-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always
